# Generated by Django 5.2 on 2025-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_image_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('brand', 'brand'), ('power', 'power')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
